version: '3.8'

services:
  app:
    image: 'golang:1.20'
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - test.env
    command: bash -c "./runDev.sh"

  db:
    image: 'mysql:8.0'
    restart: unless-stopped
    env_file:
      - test.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: